const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_BIN||'/usr/bin/chromium',args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1280,height:900}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.RECORDER_TEST_URL||'http://127.0.0.1:4004');await page.locator('#login-form [name=username]').fill('alice');await page.locator('#login-form [name=password]').fill('test-password');await page.locator('#login-form button').click();await page.getByRole('button',{name:'Open Dive',exact:true}).waitFor();
 await page.locator('nav [data-view=flight-recorder]').click();await page.getByRole('heading',{name:'Flight Recorder',exact:true}).waitFor();await page.getByRole('button',{name:'+ Schedule recording',exact:true}).click();
 await page.locator('#flight-form [name=name]').fill('Browser overnight fixture');const tomorrow=new Date(Date.now()+86400000);const date=new Date(tomorrow.getTime()-tomorrow.getTimezoneOffset()*60000).toISOString().slice(0,10);await page.locator('#flight-form [name=start]').fill(date+'T22:00');await page.locator('#flight-form [name=end]').fill('04:00');assert.match(await page.locator('#flight-window').innerText(),/6 hours/);assert.equal(await page.locator('#flight-count').innerText(),'6/6');await page.locator('#flight-form button[type=submit], #flight-form .primary').first().click();await page.getByRole('heading',{name:'Flight Recorder',exact:true}).waitFor();await page.getByRole('button',{name:'Edit',exact:true}).click();await page.locator('#flight-form [name=name]').fill('Edited overnight fixture');await page.locator('#flight-form .primary').click();await page.getByText('Edited overnight fixture',{exact:true}).first().waitFor();await page.getByRole('button',{name:'Cancel future recordings',exact:true}).click();await page.getByText('No upcoming recordings.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Record now',exact:true}).click();await page.locator('#flight-form [name=name]').fill('Browser six-stream fixture');await page.locator('#flight-form [name=duration]').fill('0.01');await page.locator('#flight-form .primary').click();await page.getByRole('heading',{name:'Flight Recorder',exact:true}).waitFor();
 // Closing the initiating tab must leave capture running on the server.
 await page.close();const returned=await context.newPage();returned.on('pageerror',e=>errors.push(e.message));await returned.goto(process.env.RECORDER_TEST_URL||'http://127.0.0.1:4004');await returned.getByRole('button',{name:'Open Dive',exact:true}).waitFor();await returned.locator('nav [data-view=flight-recorder]').click();await returned.getByRole('button',{name:'Listen',exact:true}).first().waitFor({timeout:65000});await returned.getByRole('button',{name:'Listen',exact:true}).first().click();await returned.locator('#flight-toggle').waitFor();assert.equal(await returned.locator('#source').innerText(),'RECORDER');assert.equal(await returned.locator('#now-title').innerText(),'Fixture station 1');assert.match(await returned.locator('#now-artist').innerText(),/Browser six-stream fixture/);assert.equal(await returned.locator('.player').evaluate(el=>el.classList.contains('recorder-active')),true);
 await returned.locator('#play').click();assert.equal(await returned.locator('#play').getAttribute('aria-label'),'Pause');assert.equal(await returned.locator('#flight-toggle').innerText(),'Pause');await returned.waitForTimeout(1200);assert.equal(await returned.evaluate(async()=>{const {audio}=await import('/player.js');return !audio.paused&&audio.readyState>=2&&audio.currentTime>0.5;}),true,'AAC fixture must really decode and play');const before=Number(await returned.locator('#flight-seek').inputValue());await returned.locator('[data-flight-station]').nth(1).click();const after=Number(await returned.locator('#flight-seek').inputValue());assert.ok(after>=before&&after-before<4000,'station switching must preserve shared clock');assert.equal(await returned.locator('#now-title').innerText(),'Fixture station 2');await returned.locator('#play').click();assert.equal(await returned.locator('#play').getAttribute('aria-label'),'Play');assert.equal(await returned.locator('#flight-toggle').innerText(),'Play');const paused=Number(await returned.locator('#flight-seek').inputValue());await returned.waitForTimeout(1000);assert.ok(Math.abs(Number(await returned.locator('#flight-seek').inputValue())-paused)<100,'global pause must freeze session clock');
 await returned.locator('#seek').fill('84');await returned.locator('#seek').dispatchEvent('input');await returned.waitForTimeout(300);assert.ok(Number(await returned.locator('#flight-seek').inputValue())>=30000,'global seek');

 // Footer controls still work after leaving the management view.
 await returned.locator('nav [data-view=home]').click();await returned.getByRole('button',{name:'Open Dive',exact:true}).waitFor();assert.equal(await returned.locator('#source').innerText(),'RECORDER');await returned.locator('#play').click();await returned.waitForTimeout(700);assert.equal(await returned.locator('#play').getAttribute('aria-label'),'Pause');await returned.locator('#stop').click();assert.equal(await returned.locator('.player').evaluate(el=>el.classList.contains('recorder-active')),false);
 await returned.locator('nav [data-view=flight-recorder]').click();await returned.getByRole('button',{name:'Listen',exact:true}).first().click();await returned.locator('#flight-toggle').waitFor();
 // Keep three distinct captures and exercise selection across status polling.
 await returned.evaluate(async()=>{const {flightAPI}=await import('/flight-api.js');const stations=(await flightAPI('radio/stations')).data;for(const name of ['Bulk discard fixture','Keep this recording'])await flightAPI('flight-recorder/sessions','POST',{name,stationIds:[stations[0].id],durationMs:8000});});
 await returned.locator('.flight-list article').filter({hasText:'Keep this recording'}).getByRole('button',{name:'Listen',exact:true}).waitFor({timeout:25000});await returned.locator('.flight-list article').filter({hasText:'Bulk discard fixture'}).getByRole('button',{name:'Listen',exact:true}).waitFor();assert.equal(await returned.getByRole('button',{name:'Listen',exact:true}).count(),3);
 await returned.getByRole('checkbox',{name:'Select Browser six-stream fixture',exact:true}).check();await returned.getByRole('checkbox',{name:'Select Bulk discard fixture',exact:true}).check();await returned.waitForTimeout(5500);assert.equal(await returned.getByRole('checkbox',{name:'Select Browser six-stream fixture',exact:true}).isChecked(),true);assert.equal(await returned.locator('#flight-delete-selected').innerText(),'Delete selected (2)');
 returned.once('dialog',dialog=>dialog.dismiss());await returned.locator('#flight-delete-selected').click();assert.equal(await returned.getByRole('button',{name:'Listen',exact:true}).count(),3);
 await returned.setViewportSize({width:390,height:844});assert.equal(await returned.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await returned.screenshot({path:'test-results/recorder-browser-mobile.png',fullPage:true});returned.once('dialog',dialog=>dialog.accept());await returned.locator('#flight-delete-selected').click();await returned.getByRole('strong').filter({hasText:'Browser six-stream fixture'}).waitFor({state:'hidden'});await returned.getByRole('strong').filter({hasText:'Bulk discard fixture'}).waitFor({state:'hidden'});await returned.locator('#flight-toggle').waitFor({state:'hidden'});assert.equal(await returned.locator('.player').evaluate(el=>el.classList.contains('recorder-active')),false);assert.equal(await returned.getByRole('button',{name:'Listen',exact:true}).count(),1);assert.equal(await returned.getByRole('checkbox',{name:'Select Keep this recording',exact:true}).isChecked(),false);
 await returned.locator('#flight-select-all').check();assert.equal(await returned.getByRole('checkbox',{name:'Select Keep this recording',exact:true}).isChecked(),true);await returned.locator('#flight-select-all').uncheck();assert.equal(await returned.locator('#flight-delete-selected').isDisabled(),true);
 assert.deepEqual(errors,[]);await browser.close();console.log('PASS: scheduling, tab-close capture, AAC playback, persistent Now Playing and footer play/pause/seek/stop, station switching, multiple recordings, bulk selection/cancel/delete preserves unselected recording, mobile.');
})().catch(e=>{console.error(e);process.exit(1)});
