const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_BIN||'/usr/bin/chromium',args:['--no-sandbox']});
 const context=await browser.newContext({viewport:{width:1280,height:900}});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.RECORDER_TEST_URL||'http://127.0.0.1:4004');await page.locator('#login-form [name=username]').fill('alice');await page.locator('#login-form [name=password]').fill('test-password');await page.locator('#login-form button').click();await page.getByRole('button',{name:'Open Dive',exact:true}).waitFor();
 await page.locator('nav [data-view=flight-recorder]').click();await page.getByRole('heading',{name:'Flight Recorder',exact:true}).waitFor();await page.getByRole('button',{name:'+ Schedule recording',exact:true}).click();
 await page.locator('#flight-form [name=name]').fill('Browser overnight fixture');const tomorrow=new Date(Date.now()+86400000);const date=new Date(tomorrow.getTime()-tomorrow.getTimezoneOffset()*60000).toISOString().slice(0,10);await page.locator('#flight-form [name=start]').fill(date+'T22:00');await page.locator('#flight-form [name=end]').fill('04:00');assert.match(await page.locator('#flight-window').innerText(),/6 hours/);assert.equal(await page.locator('#flight-count').innerText(),'6/6');await page.locator('#flight-form button[type=submit], #flight-form .primary').first().click();await page.getByRole('heading',{name:'Flight Recorder',exact:true}).waitFor();await page.getByRole('button',{name:'Edit',exact:true}).click();await page.locator('#flight-form [name=name]').fill('Edited overnight fixture');await page.locator('#flight-form .primary').click();await page.getByText('Edited overnight fixture',{exact:true}).first().waitFor();await page.getByRole('button',{name:'Cancel future recordings',exact:true}).click();await page.getByText('No upcoming recordings.',{exact:true}).waitFor();
 await page.getByRole('button',{name:'Record now',exact:true}).click();await page.locator('#flight-form [name=name]').fill('Browser six-stream fixture');await page.locator('#flight-form [name=duration]').fill('0.01');await page.locator('#flight-form .primary').click();await page.getByRole('heading',{name:'Flight Recorder',exact:true}).waitFor();
 // Closing the initiating tab must leave capture running on the server.
 await page.close();const returned=await context.newPage();await returned.goto(process.env.RECORDER_TEST_URL||'http://127.0.0.1:4004');await returned.getByRole('button',{name:'Open Dive',exact:true}).waitFor();await returned.locator('nav [data-view=flight-recorder]').click();await returned.getByRole('button',{name:'Listen',exact:true}).first().waitFor({timeout:65000});await returned.getByRole('button',{name:'Listen',exact:true}).first().click();await returned.locator('#flight-toggle').waitFor();
 await returned.locator('#flight-toggle').click();await returned.waitForTimeout(1200);assert.equal(await returned.evaluate(async()=>{const {audio}=await import('/player.js');return !audio.paused&&audio.readyState>=2&&audio.currentTime>0.5;}),true,'AAC fixture must really decode and play');const before=Number(await returned.locator('#flight-seek').inputValue());await returned.locator('[data-flight-station]').nth(1).click();const after=Number(await returned.locator('#flight-seek').inputValue());assert.ok(after>=before&&after-before<4000,'station switching must preserve shared clock');await returned.locator('#flight-toggle').click();const paused=Number(await returned.locator('#flight-seek').inputValue());await returned.waitForTimeout(1000);assert.ok(Math.abs(Number(await returned.locator('#flight-seek').inputValue())-paused)<100,'global pause must freeze session clock');
 await returned.locator('#flight-seek').fill('30000');await returned.locator('#flight-seek').dispatchEvent('input');await returned.waitForTimeout(300);assert.ok(Number(await returned.locator('#flight-seek').inputValue())>=30000,'global seek');
 await returned.setViewportSize({width:390,height:844});assert.equal(await returned.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await returned.screenshot({path:'test-results/recorder-browser-mobile.png',fullPage:true});returned.on('dialog',dialog=>dialog.accept());await returned.locator('.flight-list article').filter({hasText:'Browser six-stream fixture'}).getByRole('button',{name:'Delete server recording',exact:true}).click();await returned.getByRole('strong').filter({hasText:'Browser six-stream fixture'}).waitFor({state:'hidden'});await returned.locator('#flight-toggle').waitFor({state:'hidden'});assert.deepEqual(errors,[]);await browser.close();console.log('PASS: overnight scheduling/edit/cancel, six-stream capture survives tab closure, shared playback switch/pause/seek, deletion, mobile.');
})().catch(e=>{console.error(e);process.exit(1)});
