const assert = require('node:assert/strict');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async () => {
  const browser = await chromium.launch({headless:true, executablePath:process.env.BROWSER_BIN || '/usr/bin/chromium', args:['--no-sandbox']});
  const context = await browser.newContext({viewport:{width:1440,height:1000}});
  const page = await context.newPage();
  await page.addInitScript(() => {
    const NativeEventSource = window.EventSource;
    window.metadataSources = [];
    window.EventSource = class extends NativeEventSource {
      constructor(...args) {super(...args);window.metadataSources.push(this);}
      close() {this.wasClosed = true;super.close();}
    };
  });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:4002');
  assert.equal(await page.locator('link[rel=icon]').getAttribute('href'),'/weazlhead.png');
  await page.locator('#auth-mode').click();
  await page.locator('#login-form input[name=username]').fill('web-alice');
  await page.locator('#login-form input[name=password]').fill('web-password-long');
  await page.locator('#login-form button').click();
  await page.locator('#connection-form input[name=url]').fill('http://127.0.0.1:4534');
  await page.locator('#connection-form input[name=username]').fill('alice');
  await page.locator('#connection-form input[name=password]').fill('test-password');
  await page.locator('#connection-form button').click();
  await page.getByRole('button',{name:'Open Dive',exact:true}).waitFor();
  await page.locator('.album-art').first().evaluate(image => image.decode());
  const box = await page.locator('.album-art').first().boundingBox();
  assert.ok(Math.abs(box.width - box.height) < 1, 'album art must remain square');
  assert.ok(await page.locator('#fresh-shelf').evaluate(e => e.scrollWidth > e.clientWidth), 'recent albums should overflow horizontally');
  await page.getByRole('button',{name:'Next recent albums',exact:true}).click();
  assert.ok(await page.locator('#fresh-shelf').evaluate(e => e.scrollLeft > 0), 'shelf arrow should scroll');
  await page.getByRole('button',{name:'Previous recent albums',exact:true}).click();
  assert.equal(await page.locator('#sidebar-playlists').count(),0);
  await page.setViewportSize({width:1440,height:350});
  assert.ok(await page.locator('.sidebar').evaluate(e => e.scrollHeight > e.clientHeight), 'sidebar should overflow');
  await page.locator('.sidebar').evaluate(e => { e.scrollTop = e.scrollHeight; });
  assert.ok(await page.locator('.sidebar').evaluate(e => e.scrollTop > 0), 'sidebar should scroll down');
  await page.setViewportSize({width:1440,height:1000});
  await page.locator('.sidebar').evaluate(e => { e.scrollTop = 0; });
  await page.locator('[data-action=resume]').click();
  await page.waitForFunction(() => document.querySelector('#play').getAttribute('aria-label') === 'Pause');
  assert.equal(await page.locator('#queue-count').innerText(),'30');
  await page.locator('#play').click();
  await page.locator('#account').click();
  await page.locator('#configure-llm').click();
  await page.locator('#llm-form [name=provider]').selectOption('ollama');
  await page.locator('#llm-form [name=url]').fill('http://127.0.0.1:4534');
  await page.locator('#load-models').click();
  await page.waitForFunction(() => document.querySelector('#llm-form [name=model]').value === 'fixture-model');
  await page.getByRole('button',{name:'Save curator settings',exact:true}).click();
  await page.locator('#modal').waitFor({state:'hidden'});
  const seedTitle = await page.locator('#now-title').innerText();
  await page.locator('#build-mood').click();
  await page.waitForFunction(() => document.querySelectorAll('.track-row').length > 1 && document.querySelectorAll('.track-row').length < 20);
  await page.waitForFunction(() => document.querySelector('#mood-progress').textContent === 'Mood 20/20');
  assert.equal(await page.locator('.track-row').count(),20);
  assert.equal(await page.locator('#now-title').innerText(),seedTitle);
  assert.equal(await page.locator('#play').getAttribute('aria-label'),'Play');
  await page.locator('nav [data-view=home]').click();
  await page.screenshot({path:'/tmp/weazltunes-live-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Open Dive',exact:true}).click();
  await page.getByRole('button',{name:'Play album',exact:false}).click();
  await page.waitForFunction(() => document.querySelector('#play').getAttribute('aria-label') === 'Pause');
  assert.equal(await page.locator('#queue-count').innerText(),'02');
  await page.locator('#favorite').click();
  await page.waitForFunction(() => document.querySelector('#favorite').getAttribute('aria-pressed') === 'true');
  await page.locator('#play').click();
  await page.locator('nav [data-view=queue]').click();
  await page.getByRole('heading',{name:'The queue is yours.'}).waitFor();
  await page.locator('#content [data-move]').nth(1).click();
  await page.locator('#save-queue').click();
  await page.locator('#playlist-form input').fill('Browser test mixtape');
  await page.getByRole('button',{name:'Save to Navidrome',exact:false}).click();
  await page.getByRole('heading',{name:'Browser test mixtape',exact:true}).waitFor();
  assert.equal(await page.locator('.track-row').count(),3);
  await page.getByRole('button',{name:'Rename',exact:true}).click();
  await page.locator('#playlist-form input').fill('Renamed browser mixtape');
  await page.getByRole('button',{name:'Save to Navidrome',exact:false}).click();
  await page.getByRole('heading',{name:'Renamed browser mixtape',exact:true}).waitFor();
  await page.locator('[data-playlist-remove]').first().click();
  await page.waitForFunction(() => document.querySelectorAll('.track-row').length === 2);
  await page.locator('#search').fill('Radiohead');
  await page.getByRole('heading',{name:'Results for “Radiohead”'}).waitFor();
  assert.equal(await page.locator('.track-row').count(),9);
  await page.locator('nav [data-view=radio]').click();
  await page.waitForFunction(() => document.querySelectorAll('.station').length === 7);
  const names = await page.locator('.station h3').allTextContents();
  assert.equal(names[0],'DEF CON Radio');assert.equal(names[1],'80s 90s Super Pop Hits');
  const sampleAudio = await context.request.get(new URL('/api/media/stream?id=0-0',page.url()).href);
  const wav = await sampleAudio.body();
  await page.route('**/api/radio/stream?*',route => route.fulfill({status:200,contentType:'audio/wav',body:wav}));
  await page.route('**/api/radio/events?*',route => route.fulfill({status:200,contentType:'text/event-stream',body:'data: {"title":"Billie Jean","artist":"Michael Jackson"}\n\n'}));
  const station = page.locator('.station').filter({has:page.getByRole('heading',{name:'80s 90s Super Pop Hits',exact:true})});
  const queueBeforeRadio = await page.locator('#queue-count').innerText();
  await station.getByRole('button',{name:'Tune in',exact:false}).click();
  await page.waitForFunction(() => document.querySelector('#now-title').textContent === 'Billie Jean' && document.querySelector('#play').getAttribute('aria-label') === 'Pause');
  assert.equal(await page.locator('#now-artist').innerText(),'Michael Jackson · 80s 90s Super Pop Hits');
  assert.equal(await page.locator('#queue-count').innerText(),queueBeforeRadio);
  assert.equal(await page.evaluate(() => navigator.mediaSession.metadata.title),'Billie Jean');
  await page.locator('#play').click();
  assert.ok(await page.evaluate(() => window.metadataSources.every(source => source.wasClosed)), 'pause must close metadata connections');
  assert.equal(await page.locator('#now-title').innerText(),'80s 90s Super Pop Hits');
  assert.equal(await page.locator('#now-artist').innerText(),'Live radio');
  await page.unroute('**/api/radio/stream?*');await page.unroute('**/api/radio/events?*');

  await page.locator('input[name=name]').fill('Test station');
  await page.locator('input[name=url]').fill('https://example.com/test.mp3');
  await page.getByRole('button',{name:'Add station',exact:false}).click();
  await page.getByRole('heading',{name:'Test station',exact:true}).waitFor();
  await page.waitForResponse(response => response.url().endsWith('/api/state') && response.request().method() === 'PUT');
  await page.reload();
  await page.getByRole('button',{name:'Open Dive',exact:true}).waitFor();
  await page.locator('nav [data-view=radio]').click();
  await page.getByRole('button',{name:'My stations',exact:true}).click();
  await page.getByRole('heading',{name:'Test station',exact:true}).waitFor();
  await page.locator('nav [data-view=playlists]').click();
  await page.getByRole('button',{name:/Renamed browser mixtape/}).last().click();
  await page.getByRole('heading',{name:'Renamed browser mixtape',exact:true}).waitFor();
  await page.getByRole('button',{name:'Delete',exact:true}).click();
  await page.locator('#confirm-delete').click();
  await page.getByRole('heading',{name:'Handpicked. Zero filler.'}).waitFor();
  await page.locator('#account').click();
  await page.getByRole('button',{name:'Sign out',exact:true}).click();
  await page.locator('#login-screen').waitFor({state:'visible'});
  const denied = await context.request.get(new URL('/api/state',page.url()).href);
  assert.equal(denied.status(),401);
  await page.locator('#auth-mode').click();
  await page.locator('#login-form input[name=username]').fill('web-bob');
  await page.locator('#login-form input[name=password]').fill('web-password-long');
  await page.locator('#login-form button').click();
  await page.locator('#connection-form input[name=url]').fill('http://127.0.0.1:4534');
  await page.locator('#connection-form input[name=username]').fill('bob');
  await page.locator('#connection-form input[name=password]').fill('test-password');
  await page.locator('#connection-form button').click();
  await page.getByRole('button',{name:'Open Dive',exact:true}).waitFor();
  assert.equal(await page.locator('#queue-count').innerText(),'00');
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:'/tmp/weazltunes-live-mobile.png',fullPage:true});
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth),false);
  await page.locator('#help').click();await page.locator('#mobile-account').click();
  await page.getByRole('button',{name:'Sign out',exact:true}).waitFor();
  assert.deepEqual(errors,[]);
  await browser.close();
  console.log('PASS: login, random play + 30 queued, LLM settings, streaming Mood, real audio, queue, favorite, Navidrome playlist create/rename/remove/delete, search, installed presets, ICY metadata UI/lifecycle, favicon, persistence, logout, second-user isolation, mobile.');
})().catch(error => {console.error(error);process.exit(1);});
